### ISSUE TITLE
Portals Dont Delete :3

### ISSUE THREAD

**Issue by ghost** [shwayn3/Stargate#1]
Just like in MineGate the portal does not deconstruct or delete once it has been removed. You should just set it to remove its data line in the text file as soon as its sign is removed. I removed the ENTIRE portal all of its blocks etc lol and it was still showing up on the teleport lists etc. >.<

Im majorcyto on the hey0 forums.

**Comment by ghost** [comment]
Never mind, the issue is that if i delete it with a degriefing plugin tool (isntantly delete it) then it does not register the deletion. But if i delete it normally by hitting the sign like a player it removed the teleport.

Sorry about this. >.<

**Comment by shwayn3** [comment]
Yeah I was going to say.

This also happens if you use Super Pick from World Edit.

If you accidentally do this, just replace the parts you broke, and the gate will be there like normal. :)

However avoid hitting off the sign, that's just hazardous. D:
