### ISSUE TITLE
Stargate Refusing to work

### ISSUE THREAD

**Issue by Jeteye** [shwayn3/Stargate#10]
Im have trouble getting the Stargate mod to work at all. I'm running it with hey0 server mod. I downloaded the jar file and put it in the plugins folder. Added stargate to the plugin list in the server properties file. I put the scr folder and read me file in the same folder as hey0 and all its files. When I start the server a command window appears and loads the world. Once the world is loaded it produces a message that says "stargate was enabled".  When I log in I create a gate just like the forums say. A 4 block base and top of obsidian with 3 blocks risings up, creating a 2X3 opening in the obsidian. I place a sign on the middle block and type the name in the first line. When I click done nothing happens. No message, no button, nothing. If anyone can help me or tell me what I'm doing wrong that would be great. If you need more info feel free to ask. Thanks to anyone who helps.

**Comment by Dinnerbone** [comment]
What name(s) are you trying on the gate? Any errors in the console? Do you have any other gates working? Can you please take a screenshot of the gate with the sign on it.

**Comment by Jeteye** [comment]
Im using home, city, ocean, coliseum, test 1, test 2. I get no errors in the console, nor does the server lag like its trying to do something. I have no gates working period. I took a screen shot but I don't know how to load it so you can see it. Thanks for trying to help .

**Comment by Dinnerbone** [comment]
Try www.imgur.com

**Comment by Jeteye** [comment]
Ok I uploaded the screenshot to imgur. Here's the link: http://jeteye.imgur.com/all/. I also uploaded a picture of my console right after I placed a sign on the portal. The lines that say "[WARNING] Can't keep it up! Did the system time change or is the server overloaded." Aren't any issue. I get those all the time and they appeared when the server started.

**Comment by Jeteye** [comment]
Thanks for the help Dinnerbone. I got Stargate to work. I thought I was an admin in the server but I added the name to the group wrong and was placed as a normal player that cant create warp. Now that it see me as am admin I can create warps. Thanks again for the help.
